### ISSUE TITLE
USER STORY 2: Submit a Poll Response

### ISSUE THREAD

**Issue by GaryCooper-pm** [GaryCooper-pm/My-First-Agile-Project#4]
In order to **provide anonymous feedback** as a **user**, I can **choose to hide my identity in the poll response.**

**Comment by GaryCooper-pm** [comment]
# Acceptance Criteria:
* The poll should disappear at 11.59 PM on the target date
* The real estate of the "Poll" should be reserved on the home page.  A message that says "Stay Tuned, a new poll is coming soon" should appear if no other Poll is active.
* The administrator expiry date should be at least 3 days after the current date.
# Tasks:
- [ ] Update the admin module view: the poll design (HTML and CSS) to include date picker
- [ ] Update the website view: "Stay tuned, a new poll is coming soon"
- [ ] create Javascript function to validate the expiry date is at least after 3 days.
- [ ] Create a job to check expired Polls everyday at 11:59 PM and Hide them
- [ ] Update the controller function
- [ ] Update unit test scripts
- [ ] Test the functionality
